name: remote_hooks
description: A CLI tool to share & install git hooks from remote repository
version: 1.0.3
repository: https://github.com/SilentCatD/remote_hooks
issue_tracker: https://github.com/SilentCatD/remote_hooks/issues

topics:
  - cli
  - githooks
  - pre-commit
  - generator

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  cli_util: ^0.4.2
  io: ^1.0.5
  meta: ^1.12.0
  path: ^1.9.0
  uuid: ^4.5.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
