name: remote_hooks
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  dart_mappable: ^4.3.1
  mason_logger: ^0.2.16
  path: ^1.9.1
  pub_updater: ^0.4.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  coverage: ^1.11.1
  dart_mappable_builder: ^4.3.1+1
  io: ^1.0.5
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  remote_hooks:
